[project]
name = "mcp-ui-moviepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.5",
    "mcp-ui>=0.1.2",
    "moviepy>=2.2.1",
    "opencv-contrib-python>=4.13.0.92",
]
